---
- name: "Preflight - Fail if target host is not stable for this Role."
  ansible.builtin.fail:
    msg: "This role is not stable for the target operating system, {{ ansible_distribution }} {{ ansible_distribution_major_version }}."
  when: (ansible_distribution is not defined) or
        (ansible_distribution_version is not defined) or
        (ansible_distribution+" "+ansible_distribution_major_version not in checkmk_server_stable_os)

- name: "Include OS Family specific Variables."
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Install Checkmk Prerequisites."
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ checkmk_prerequisites}}"

- name: "Download Checkmk Server Setup."
  ansible.builtin.get_url:
    url: "{{ checkmk_download_url }}"
    dest: "/tmp/{{ checkmk_setup_file }}"

- name: Include OS Family specific Playbook.
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: "Create Sites."
  ansible.builtin.shell: "omd create {{ item.name }}"
  args:
    creates: "/omd/sites/{{ item.name }}"
  no_log: 'true'
  loop: "{{ checkmk_sites }}"
  when: item.state != "absent"
  register: checkmk_sites_created

- name: "Start Sites."
  ansible.builtin.shell: "omd start {{ item.name }}"
  args:
    creates: "/opt/omd/sites/{{ item.name }}/tmp/run/live"
  no_log: 'true'
  loop: "{{ checkmk_sites }}"
  when: item.state == "started"
  register: checkmk_sites_started

- name: "Stop Sites."
  ansible.builtin.shell: "omd stop {{ item.name }}"
  args:
    removes: "/opt/omd/sites/{{ item.name }}/tmp/run/live"
  no_log: 'true'
  loop: "{{ checkmk_sites }}"
  when: (item.state == "absent") or (item.state == "stopped")
  register: checkmk_sites_stopped

- name: "Destroy Sites."
  ansible.builtin.shell: "yes yes | omd rm {{ item.name }}"
  args:
    removes: "/omd/sites/{{ item.name }}"
  no_log: 'true'
  loop: "{{ checkmk_sites }}"
  when: item.state == "absent"
  register: checkmk_sites_removed

- name: "Update Site Admin Password."
  ansible.builtin.shell: "echo '{{ item.admin_pw }}' | htpasswd -i /omd/sites/{{ item.name }}/etc/htpasswd cmkadmin"
  no_log: 'true'
  loop: "{{ checkmk_sites }}"
  when: item.state != "absent"

- name: "Create self-signed Certificate."
  command: 'openssl req -new -nodes -x509 -subj "{{ checkmk_self_signed_cert_subj }}" -days 365 -keyout {{ checkmk_self_signed_certificate_key }} -out {{ checkmk_self_signed_certificate }} -extensions v3_ca'
  args:
    creates: "{{ checkmk_self_signed_certificate }}"
  when: checkmk_create_self_signed_cert | bool

- name: "Enable Apache2 SSL Module."
  apache2_module:
    name: ssl
    state: present
  notify: restart webserver

- name: "Copy Checkmk Configuration File for Apache2."
  template:
    src: checkmk.conf.j2
    dest: "{{ apache2_http_site_dir }}/checkmk.conf"
    owner: root
    group: root
    mode: '0600'
    backup: 'yes'
    force: 'yes'
  notify: reload webserver

- name: "Enable Checkmk Configuration."
  command: a2ensite checkmk.conf
  args:
    creates: "/etc/apache2/sites-enabled/checkmk.conf"
  notify: reload webserver
  when: ansible_os_family == "Debian"
